import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Blogs() {
  return (
    <>
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
      {/* <Image
                  src="https://live.staticflickr.com/65535/53457230978_912df9e01e_o.jpg"
                  alt="hero images"
                  className={styles.vercelLogo}
                  width={100}
                  height={24}
                  priority
                  /> */}
      </main>
    </>
  );
}
